# Project 3- Sonar, Rocks & Mines

We are going to perform analysis on Sonar, Rocka and Mines dataset. The input data is in .csv format with 207 obsevations. The dataset has total 60 columns with the below description


Our Target Variable is "Column 60" - depicting Rocks or Mines

# Loading Dataset

In [16]:
import pandas as pd
df=pd.read_csv("Sonar.csv",names=range(0,61),header=0)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

       9   ...      51      52      53      54      55      56      57  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

       58      59  60  
0  0.0052  0.0044   R  
1  0.0095  0.0078   R  
2  0.0040  0.0117   R  
3  0.0107  0.0094   R  
4  0.0051  0.0062   R  

[5 rows x 61 columns]

In [5]:
df.shape

(207, 61)

In [6]:
df.info

<bound method DataFrame.info of      0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

     0.2111  ...  0

# Importing Required Libraries

In [39]:
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       207 non-null    float64
 1   1       207 non-null    float64
 2   2       207 non-null    float64
 3   3       207 non-null    float64
 4   4       207 non-null    float64
 5   5       207 non-null    float64
 6   6       207 non-null    float64
 7   7       207 non-null    float64
 8   8       207 non-null    float64
 9   9       207 non-null    float64
 10  10      207 non-null    float64
 11  11      207 non-null    float64
 12  12      207 non-null    float64
 13  13      207 non-null    float64
 14  14      207 non-null    float64
 15  15      207 non-null    float64
 16  16      207 non-null    float64
 17  17      207 non-null    float64
 18  18      207 non-null    float64
 19  19      207 non-null    float64
 20  20      207 non-null    float64
 21  21      207 non-null    float64
 22  22

Since the dataset comprises of float datatype and the target column (60) is of object datatype encoding is needed

In [18]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

Statistical analysis shows that there are no null values 

In [19]:
df.describe()

0           1           2           3           4           5   \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.029208    0.038443    0.043837    0.054053    0.075105    0.104599   
std      0.023038    0.033040    0.038521    0.046583    0.055669    0.059247   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013300    0.016400    0.018900    0.024450    0.037700    0.066950   
50%      0.022800    0.030800    0.034200    0.044100    0.062000    0.092100   
75%      0.035800    0.048100    0.058200    0.065700    0.101050    0.134150   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  207.000000  207.000000  207.000000  207.000000  ...  207.000000   
mean     0.121591    0.134677    0.177361    0.208245  ...    0.016034   
std      0.061897    0.085340    0.118311    0.134741  ...    0.012027   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080600    0.080350    0.096750    0.111150  ...    0.008350   
50%      0.105600    0.111900    0.152200    0.181000  ...    0.013800   
75%      0.153050    0.169800    0.231500    0.269000  ...    0.020700   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.013472    0.010729    0.010917    0.009300    0.008181    0.007771   
std      0.009628    0.007071    0.007310    0.007103    0.005719    0.005756   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007350    0.005050    0.005350    0.004100    0.004400    0.003700   
50%      0.011500    0.009600    0.009300    0.007500    0.006800    0.005900   
75%      0.016750    0.014900    0.014450    0.012100    0.010350    0.010350   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  207.000000  207.000000  207.000000  
mean     0.007947    0.007936    0.006523  
std      0.006485    0.006196    0.005038  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003650    0.003100  
50%      0.005800    0.006300    0.005300  
75%      0.010400    0.010350    0.008550  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

This denotes:

1. That there are no missing values as count is similar for all columns
2. There isn't much difference between the mean and median, hence there are no much outliers. We will validate it futher as well


# EDA

In [20]:
df.corr()

0         1         2         3         4         5         6   \
0   1.000000  0.736104  0.571706  0.490853  0.345744  0.238824  0.262095   
1   0.736104  1.000000  0.779915  0.607297  0.419877  0.332319  0.279328   
2   0.571706  0.779915  1.000000  0.782662  0.546365  0.346271  0.190628   
3   0.490853  0.607297  0.782662  1.000000  0.729338  0.352901  0.248713   
4   0.345744  0.419877  0.546365  0.729338  1.000000  0.597438  0.334831   
5   0.238824  0.332319  0.346271  0.352901  0.597438  1.000000  0.703624   
6   0.262095  0.279328  0.190628  0.248713  0.334831  0.703624  1.000000   
7   0.356312  0.334747  0.237974  0.248131  0.203590  0.471942  0.675612   
8   0.356822  0.317929  0.253615  0.252048  0.176522  0.329145  0.469490   
9   0.318440  0.270787  0.219641  0.238136  0.183240  0.288639  0.425675   
10  0.343362  0.297186  0.274751  0.270466  0.232939  0.333560  0.398590   
11  0.209891  0.194177  0.214947  0.173502  0.213108  0.344499  0.276563   
12  0.210187  0.249602  0.258799  0.214868  0.299892  0.411068  0.366629   
13  0.254880  0.274222  0.292960  0.283544  0.363429  0.397477  0.415424   
14  0.303731  0.308506  0.286569  0.275610  0.321543  0.368683  0.416642   
15  0.238158  0.261986  0.237176  0.246552  0.330316  0.353836  0.365342   
16  0.137174  0.152151  0.201120  0.222172  0.327420  0.293115  0.251303   
17  0.040739  0.042791  0.120611  0.193372  0.300639  0.235693  0.209840   
18  0.055271  0.040913  0.099304  0.189679  0.340632  0.226316  0.215607   
19  0.156244  0.102391  0.103101  0.187496  0.286459  0.206741  0.197476   
20  0.117482  0.075235  0.063977  0.142038  0.205372  0.174720  0.166244   
21 -0.057911 -0.074285 -0.026889  0.034484  0.153833  0.123611  0.065006   
22 -0.165441 -0.179855 -0.073643 -0.032812  0.075604  0.063777  0.011550   
23 -0.219258 -0.196682 -0.085495 -0.104871  0.000244  0.026801  0.013242   
24 -0.295832 -0.295307 -0.214258 -0.206990 -0.067287 -0.043290 -0.057140   
25 -0.343524 -0.365852 -0.292049 -0.292614 -0.125299 -0.100447 -0.125553   
26 -0.341771 -0.337041 -0.263108 -0.294998 -0.169732 -0.129082 -0.179730   
27 -0.223621 -0.234424 -0.256756 -0.254868 -0.215730 -0.118479 -0.118205   
28 -0.198889 -0.228474 -0.290725 -0.300331 -0.284242 -0.156018 -0.130176   
29 -0.079322 -0.115695 -0.197985 -0.240418 -0.272394 -0.151912 -0.066077   
30 -0.052157 -0.056627 -0.107223 -0.197847 -0.212904 -0.055406 -0.093287   
31 -0.032132 -0.049933 -0.110192 -0.173397 -0.172355 -0.052435 -0.114024   
32 -0.031078 -0.108237 -0.170699 -0.163345 -0.201565 -0.144243 -0.128363   
33  0.034467 -0.003970 -0.099771 -0.079244 -0.144098 -0.069987 -0.082016   
34  0.102391  0.117078  0.017420  0.021555 -0.090396 -0.028161 -0.020195   
35  0.084810  0.133974  0.053707  0.045794 -0.077203 -0.022930 -0.001489   
36  0.122558  0.170108  0.108122  0.068247 -0.067150 -0.064429 -0.004612   
37  0.213242  0.218599  0.130954  0.094765 -0.010904 -0.048314  0.062985   
38  0.210456  0.187321  0.110802  0.092552  0.062042  0.031069  0.078993   
39  0.099643  0.098320  0.074118  0.044487  0.062006  0.081028  0.113280   
40  0.125258  0.188844  0.189761  0.141260  0.101802  0.075472  0.044829   
41  0.213733  0.261353  0.233447  0.144978  0.125168  0.048780 -0.028816   
42  0.206671  0.186450  0.113973  0.051597  0.063280  0.034513 -0.026402   
43  0.162076  0.134153  0.072598 -0.002933  0.028961  0.049955  0.057788   
44  0.281062  0.285939  0.180877  0.089504  0.088494  0.085727  0.109823   
45  0.319180  0.304236  0.173640  0.079546  0.082286  0.029446  0.077009   
46  0.230068  0.255784  0.179520  0.045478  0.041789  0.016545  0.099504   
47  0.204877  0.265719  0.235256  0.123738  0.083345  0.067612  0.153763   
48  0.247008  0.314031  0.223103  0.132191  0.088856  0.080573  0.195874   
49  0.271594  0.246502  0.081362  0.081211  0.065347  0.017763  0.164312   
50  0.255916  0.320931  0.238392  0.177103  0.115023  0.172210  0.182929   
51  0.354348  0.435641  0.395121  0.372377  0.269478  0.25

In [24]:
x=df.iloc[:,0:-1]
x

0       1       2       3       4       5       6       7       8   \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53      54      55      56  \
0    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
1    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
2    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
3    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
4    0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
203  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
204  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
205  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
206  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

         57      58      59  
0    0.0049  0.0052  0.0044  
1    0.0164  0.0095  0.0078  
2    0.0044  0.0040  0.0117  
3    0.0048  0.0107  0.0094  
4    0.0027  0.0051  0.0062  
..      ...     ...     ...  
202  0.0115  0.0193  0.0157  
203  0.0032  0.0062  0.0067  
204  0.0138  0.0077  0.0031  
205  0.0079  0.0036  0.0048  
206  0.0036  0.0061  0.0115  

[207 rows x 60 columns]

In [25]:
from sklearn.decomposition import PCA
pca=PCA(n_components=10)
x=pca.fit_transform(x)

In [26]:
x

array([[-0.97028528,  1.01765376,  0.83043188, ...,  0.38483746,
         0.00432916, -0.08267912],
       [-0.32443537,  0.87687629,  0.22820349, ...,  0.08107182,
         0.01418477, -0.43233413],
       [ 0.85357147,  0.69773427, -0.02360152, ..., -0.21542372,
        -0.53395533, -0.42518212],
       ...,
       [ 0.30676251, -1.1477555 ,  0.24897546, ...,  0.2278663 ,
        -0.07013224, -0.31329401],
       [-0.03808313, -0.99404889,  0.20193818, ...,  0.06950374,
        -0.02440647, -0.16530256],
       [-0.04390414, -0.91080234,  0.00916917, ..., -0.01910024,
         0.12012993, -0.13796362]])

In [27]:
x.shape

(207, 10)

In [29]:
pd.DataFrame(data=x)

0         1         2         3         4         5         6  \
0   -0.970285  1.017654  0.830432  0.120147  0.299120  0.202682 -0.226988   
1   -0.324435  0.876876  0.228203  0.868926  0.098053 -0.269122 -0.421778   
2    0.853571  0.697734 -0.023602 -0.123425 -0.584388  0.351808  0.478187   
3   -0.061337  0.226034  0.635198  0.152907  0.150982  0.081111 -0.374523   
4   -0.605423  0.901962  0.804550  0.271896  0.496832  0.464410 -0.224909   
..        ...       ...       ...       ...       ...       ...       ...   
202  0.049918 -1.028980  0.265634  0.026018 -0.014738  0.097506  0.012021   
203  0.228374 -1.149870  0.200437  0.043461  0.182020  0.010158  0.084858   
204  0.306763 -1.147756  0.248975 -0.058557  0.161337  0.013778  0.049391   
205 -0.038083 -0.994049  0.201938 -0.060790 -0.147673 -0.088874  0.018656   
206 -0.043904 -0.910802  0.009169 -0.045577 -0.030723 -0.033778  0.025213   

            7         8         9  
0    0.384837  0.004329 -0.082679  
1    0.081072  0.014185 -0.432334  
2   -0.215424 -0.533955 -0.425182  
3    0.070143  0.119454 -0.427480  
4    0.105504 -0.202842 -0.235048  
..        ...       ...       ...  
202  0.178998  0.029362 -0.268631  
203  0.266152 -0.068963 -0.307679  
204  0.227866 -0.070132 -0.313294  
205  0.069504 -0.024406 -0.165303  
206 -0.019100  0.120130 -0.137964  

[207 rows x 10 columns]

In [31]:
y=df.iloc[:,60]

In [32]:
y

0      R
1      R
2      R
3      R
4      R
      ..
202    M
203    M
204    M
205    M
206    M
Name: 60, Length: 207, dtype: object

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
pd.DataFrame(data=y)

0
0    1
1    1
2    1
3    1
4    1
..  ..
202  0
203  0
204  0
205  0
206  0

[207 rows x 1 columns]

# Scaling

In [36]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

# Determining the Best Fit Model

In [53]:
lr=LogisticRegression()
gs=GaussianNB()
dt=DecisionTreeClassifier()
svc=SVC()

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=36)

In [48]:
import sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
model=[GaussianNB(), SVC(),DecisionTreeClassifier(),LogisticRegression()]
for m in model:
    m.fit(x_train,y_train)
    m.score(x_train,y_train)
    predm=m.predict(x_test)
    print("Accuracy score of ", m, "is:")
    print(accuracy_score(y_test,predm))
    print(confusion_matrix(y_test,predm))
    print(classification_report(y_test,predm))
    print('\n')
    

Accuracy score of  GaussianNB() is:
0.7536231884057971
[[30  5]
 [12 22]]
              precision    recall  f1-score   support

           0       0.71      0.86      0.78        35
           1       0.81      0.65      0.72        34

    accuracy                           0.75        69
   macro avg       0.76      0.75      0.75        69
weighted avg       0.76      0.75      0.75        69



Accuracy score of  SVC() is:
0.8260869565217391
[[33  2]
 [10 24]]
              precision    recall  f1-score   support

           0       0.77      0.94      0.85        35
           1       0.92      0.71      0.80        34

    accuracy                           0.83        69
   macro avg       0.85      0.82      0.82        69
weighted avg       0.84      0.83      0.82        69



Accuracy score of  DecisionTreeClassifier() is:
0.7101449275362319
[[26  9]
 [11 23]]
              precision    recall  f1-score   support

           0       0.70      0.74      0.72        35
      

From the above results it is clear that with Accuracy score of 0.82 and f-1 score 0.85 SVC model is the best fit

In [54]:
import pickle
filename="Project1_titanic_test.pkl"
pickle.dump(gs, open(filename, "wb"))
